############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

#[[main]]
#name = "Travels"
#url = "categories/"
#weight = 2

[[main]]
name = "Travels"
url = "travel/"
weight = 2

#[[main]]
#name = "contact"
#url = "contact/"
#weight = 5

[[main]]
name = "Stories"
url = "blog/"
weight = 3

[[main]]
name = "about me"
url = "about/"
weight = 4

# dropdown menu
# [[main]]
# name = "Pages"
# weight = 6
# hasChildren = true

  # dropdown item
  # [[main]]
  # parent = "Pages"
 #  name = "page 1"
 #  url = "/"

  # [[main]]
 #  parent = "Pages"
  # name = "page 2"
 #  url = "/"
